const TYPES = {

    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILED: 'FETCH_POSTS_FAILED',
    
    FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
    FETCH_SINGLE_POST_SUCCESS: 'FETCH_SINGLE_POST_SUCCESS',
    FETCH_SINGLE_POST_FAILED: 'FETCH_SINGLE_POST_FAILED',

    FETCH_COMMENTS: 'FETCH_COMMENTS',
    FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
    FETCH_COMMENTS_FAILED: 'FETCH_COMMENTS_FAILED',

    ADD_COMMENT: 'ADD_COMMENT',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILED: 'ADD_COMMENT_FAILED'
}

export default TYPES;